resilience4j.circuitbreaker:
  instances:
    executeTaskCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 20
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      failureRateThreshold: 50
      waitDurationInOpenState: 30s
      automaticTransitionFromOpenToHalfOpenEnabled: true
      eventConsumerBufferSize: 10